name: Protect Prod Branch

on:
  push:
    branches:
      - prod

jobs:
  check-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check if push is from a pull request
        id: check_pr
        run: |
          EVENT=$(jq -r .event_name "$GITHUB_EVENT_PATH")
          if [ "$EVENT" == "push" ]; then
            echo "::set-output name=is_push::true"
          else
            echo "::set-output name=is_push::false"
          fi
        shell: bash

      - name: Refuse push if not from a PR
        if: steps.check_pr.outputs.is_push == 'true'
        run: |
          echo "Push to 'prod' branch is allowed because it's from a pull request."
        else
          echo "Push to 'prod' branch is not allowed. Please create a pull request."
          exit 1
